server:
  port: 8005
spring:
  application:
    name: service-apy
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.isuyu.cn:3306/tx-pay?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30
#lcn-tm地址
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: distributed-translation
