version: "3.1"

services:
  seata-server:
    container_name: seata-server
    image: seataio/seata-server:1.4.0
    hostname: seata-server
    ports:
      - 8091:8091
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=file
      - SEATA_CONFIG_NAME=file:/root/seata-config/registry
    volumes:
      - ./conf:/root/seata-config