server:
  port: 9100

spring:
  application:
    name: CLOUD-ZUUL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    enabled: true
  instance:
    hostname: localhost
    instance-id: CLOUD-ZUUL
zuul:
  #一下配置，表示忽略下面的值向微服务传播，以下配置为空表示：所有请求头都透传到后面微服务。
  #  sensitive-headers:
  routes:
    xxx:
      path: /a-forward/**
      url: forward:/myController

    #     配合 龙哥,后面两个*号，表示 所有路径都转发，一个* 表示 只转发一级。
    service-sms: /zuul-api-driver/**
    # 配合 风雨冷人
    xxxx: /zuul-api-driver/**
    #此处名字随便取
#    custom-zuul-name:
#      path: /zuul-api-driver/**
#      url: http://localhost:8080/
#service-sms:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.mashibing.cloudzuul.gray.GrayRule





management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      ##默认是never
      show-details: ALWAYS
      enabled: true
    routes:
      enabled: true