server:
  port: 8006
spring:
 #可以不配置，会走默认的 file.conf和registry.conf也可以不配
  cloud:
    alibaba:
      seata:
        tx-service-group: my_tx_group
  application:
    name: service-order
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/tx-order?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30

#lcn-tm地址
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070

