spring:
  application:
    name: SMS

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7900/eureka/
    registry-fetch-interval-seconds: 30
    enabled: true
  instance:
    lease-renewal-interval-in-seconds: 30

---
spring:
  profiles: v1

server:
  port:  8003

eureka:
  instance:
    metadata-map:
      version: v1

---
spring:
  profiles: v2
server:
  port:  8004

eureka:
  instance:
    metadata-map:
      version: v2



